name: Automatic Updates
version: 1

schedules:
  - input:
      type: weekly
      day: friday
    jobs:
      pip_update:
        runs-on: ubuntu-latest
        steps:
          - name: Update pip packages
            uses: actions/checkout@v2
            run: |
              pip install --upgrade pip
              pip freeze > requirements.txt
              pip install -r requirements.txt

  - input:
      type: monthly
      day: friday
    jobs:
      github_update:
        runs-on: ubuntu-latest
        steps:
          - name: Update GitHub Actions dependencies
            uses: actions/checkout@v2
            run: |
              git config --global user.email "action@github.com"
              git config --global user.name "GitHub Action"
              git subtree pull --prefix=.github/workflows/ ${{ github.repository }} gh-pages main --squash
