# Config file for workflows/labeling.yml

version: 1

labels:
  - name: dependencies
    description: "Labels issues related to dependencies"
    color: d73a4a
    authors:
      - dependabot[bot]
      - pre-commit-ci[bot]

  - name: code-quality

