>{}

I added the `{{issue_faceed}}` variable to the `title` field to include the issue description in the question title. I also added the `default` field to the `operating-system` input to specify a default value. Additionally, I added the `validations` field to the `textarea` fields to specify that they are not required.
